### ISSUE TITLE
GA error

### ISSUE THREAD

**Issue by nagdawi** [lacerbi/optimviz#1]
% DETERMINISTIC OBJECTIVE FUNCTION
% DETERMINISTIC OBJECTIVE FUNCTION

Local minimum found.

Optimization completed because the size of the gradient is less than
the default value of the optimality tolerance.

<stopping criteria details>

Maximum number of function evaluations exceeded: increase options.MaxFunctionEvaluations.
MCS not installed.
Maximum number of function evaluations exceeded: increase options.MaxFunctionEvaluations.
Index exceeds matrix dimensions.

Error in rosenbrock (line 17)
varargout{1} = 100*(x(:,2)-x(:,1).^2).^2+(1-x(:,1)).^2;

Error in optfun (line 70)
    [y,g] = table.fun(x);

Error in gaoutput (line 39)
    [state,optnew,changed] = feval(functions{i},options.OutputPlotFcnOptions,state,flag,args{i}{:});

Error in galincon (line 31)
[state,options] = gaoutput(FitnessFcn,options,state,currentState);

Error in ga (line 374)
            [x,fval,exitFlag,output,population,scores] = galincon(FitnessFcn,nvars, ...

Error in demo_opt (line 40)
ga(@optfun,2,[],[],[],[],LB,UB,[],struct('Generations',12,'OutputFcns',@optfun,'PopulationSize',25));

----------------
% MULTIMODAL OBJECTIVE FUNCTION

Undefined operator '.*' for input arguments of type 'optim.options.GaOptions'.

Error in ackley (line 14)
    varargout{1} = -20 * exp(-0.2 * sqrt( sum(x .* x, 2)/ 2)) ...

Error in optfun (line 70)
    [y,g] = table.fun(x);

Error in gaoutput (line 39)
    [state,optnew,changed] = feval(functions{i},options.OutputPlotFcnOptions,state,flag,args{i}{:});

Error in galincon (line 31)
[state,options] = gaoutput(FitnessFcn,options,state,currentState);

Error in ga (line 374)
            [x,fval,exitFlag,output,population,scores] = galincon(FitnessFcn,nvars, ...

Error in demo_opt (line 110)
ga(@optfun,2,[],[],[],[],LB,UB,[],struct('Generations',12,'OutputFcns',@optfun,'PopulationSize',25));

**Comment by lacerbi** [comment]
Mmh, no idea what's causing this, I can't reproduce it.
Clearly, it's something to do with ga (genetic algorithms). 
optimviz runs correctly on R2017a, and you need the Global Optimization toolbox, which seems you have here. optimiviz should work with a few older versions of Matlab but not sure how far in the past. Which version of Matlab are you trying this with?

**Comment by nagdawi** [comment]
my matlab ver is 2017a

**Comment by lacerbi** [comment]
Then no idea. Anyhow, "demo_opt" is an old script (in the "oldies" folder), you should be running optimviz.m.
